base/urls.py
from django.urls import path
from base import views


app_name = 'base'

urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("about-us/", views.AboutUsView.as_view(), name='about'),
    path("contact-us/", views.ContactView.as_view(), name='contact'),
    path("dashboard/", views.DashboardView.as_view(), name='dashboard'),
    path("profile/", views.EditUser.as_view(), name='profile'),
]

wsite/urls.py
from django.urls import path
from wsite import views, ajax_views


app_name = 'wsite'

urlpatterns = [
    path('', views.ListWebsiteView.as_view(), name='wsites'),
    path('create-site/', views.CreateWebsiteView.as_view(), name='create-site'),
    path('<str:slug>/', views.RetrieveWebsiteView.as_view(), name='site'),
    path('<str:slug>/add-email/', ajax_views.AddEmailView.as_view(), name='add-email'),
    path('<str:slug>/remove-email/', ajax_views.RemoveEmailView.as_view(), name='remove-email'),
    path('<str:slug>/delete/', views.DeleteWebsiteView.as_view(), name='delete-site'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from sdtmonitor.utils.strings import get_slug_text
# Create your models here.


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["email"]

    email = models.EmailField(verbose_name="email address", unique=True)
    username = models.CharField(max_length=255, unique=True, default=get_slug_text)
    objects = UserManager()

    def __str__(self):
        return self.get_full_name() or self.email

base/forms.py
from django import forms
from sdtmonitor.utils.forms import CssForm
from base.models import User

class UserForm(forms.ModelForm, CssForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', ]

base/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from django.contrib import messages
from plan.models import Plan
from django.contrib.auth.mixins import LoginRequiredMixin
from base.forms import UserForm
from wsite.models import Website
from datetime import datetime
# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['plans'] = Plan.objects.all()
        return context


class AboutUsView(TemplateView):
    template_name = 'about.html'


class ContactView(TemplateView):
    template_name = 'contact.html'



class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    def greeting(self):
        """Function Goes"""
        current_date_time = datetime.now()
        if current_date_time.hour < 12:
            return 'Good Morning'
        else:
            return 'Good Afternoon'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['websites'] = Website.objects.filter(user=self.request.user)[:5]
        context['greeting'] = self.greeting()
        return context

class EditUser(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        template_name = 'profile.html'
        context = {
            'form' : UserForm(instance=self.request.user)
        }
        return render(request, template_name, context)
    
    def post(self, request, *args, **kwargs):
        form = UserForm(request.POST, instance=self.request.user)
        form.save()
        messages.success(request, 'Profile Updated Successfully')
        return redirect("base:profile")

'''
Update Profile
Subscription Page
'''

base/templates/partials/_auth_footer.html
<div class="main-footer">
    <div class="col-md-12 col-sm-12 text-center">
        <div class="container-fluid pt-0 ht-100p"> Copyright © <script>document.write(new Date().getFullYear())</script> <a href="javascript:void(0);"
                class="text-primary">SDTMonitor</a>. All rights reserved </div>
    </div>
</div>

base/templates/partials/_auth_layout.html
<!DOCTYPE html>
{% load static i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="Description" content="Website Downtime Monitor">
    <meta name="Author" content="">
    <meta name="Keywords" content="Monitor Website Downtime, Server Monitor" />
    <title>{% block title %} {% endblock title  %} - Server Monitor</title>
    <meta http-equiv="imagetoolbar" content="no" />
    {% include 'partials/_auth_stylesheet.html' %}
    {% block extra_styles %} {% endblock extra_styles %}
</head>

<body class="ltr main-body app sidebar-mini">
    <div id="global-loader" style="display: none;"> <img src="{% static 'img/loader.svg' %}" class="loader-img" alt="Loader"> </div>
    <div class="page">
        {% block body %}
        <div class="open">
            <!-- main-header -->

            {% include 'partials/_auth_navbar.html' %}
             <!-- /main-header -->
            <!-- main-sidebar -->
            {% include 'partials/_auth_sidebar.html' %}
            <!-- main-sidebar -->
            <div class="main-content app-content">
                <!-- container -->
                <div class="main-container container-fluid">
                    <!-- breadcrumb -->
                    <div class="breadcrumb-header justify-content-between">
                        <div class="left-content"> <span class="main-content-title mg-b-0 mg-b-lg-1">{% block breadcrumb_title %}DASHBOARD{% endblock breadcrumb_title %}</span> </div>
                        <div class="justify-content-center mt-2">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item tx-15"><a href="javascript:void(0);">Dashboard</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Sales</li>
                            </ol>
                        </div>
                    </div> <!-- /breadcrumb -->
                    <!-- row -->
                    {% include "partials/_messages.html" %}
                    {% block content %} {% endblock content %}
                </div> <!-- /Container -->
            </div> <!-- /main-content -->
            
            {% include 'partials/_auth_footer.html' %}
        </div> 
    
        {% endblock body %}
    </div>
    <a href="#top" id="back-to-top" style="display: none;"><i class="las la-arrow-up"></i></a>
    {% include 'partials/_auth_script.html' %}
    {% block extra_scripts %} {% endblock extra_scripts %}
</body>

</html>

base/templates/partials/_auth_navbar.html
{% load static i18n %}
<div class="main-header side-header sticky nav nav-item" style="margin-bottom: -63px;">
    <div class=" main-container container-fluid">
        <div class="main-header-left ">
            <div class="responsive-logo"> <a href="index.html" class="header-logo">
                    <img src="{% static 'img/brand/logo.png' %}" class="mobile-logo logo-1" alt="logo">
                    <img src="{% static 'img/brand/logo-white.png' %}" class="mobile-logo dark-logo-1" alt="logo">
                </a>
            </div>
            <div class="app-sidebar__toggle" data-bs-toggle="sidebar">
                <a class="open-toggle" href="javascript:void(0);">
                    <i class="header-icon fe fe-align-left"></i>
                </a>
                <a class="close-toggle" href="javascript:void(0);">
                    <i class="header-icon fe fe-x"></i></a>
            </div>
            <div class="logo-horizontal">
                <a href="index.html" class="header-logo">
                    <img src="{% static 'img/brand/logo.png' %}" class="mobile-logo logo-1" alt="logo">
                    <img src="{% static 'img/brand/logo-white.png' %}" class="mobile-logo dark-logo-1" alt="logo">
                </a>
            </div>
            <div class="main-header-center ms-4 d-sm-none d-md-none d-lg-block form-group">
                <input class="form-control" placeholder="Search..." type="search">
                <button class="btn"><i class="fas fa-search"></i></button>
            </div>
        </div>
        <div class="main-header-right">
            <button class="navbar-toggler navresponsive-toggler d-lg-none ms-auto" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent-4"
                aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon fe fe-more-vertical "></span>
            </button>
            <div class="mb-0 navbar navbar-expand-lg navbar-nav-right responsive-navbar navbar-dark p-0">
                <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                    <ul class="nav nav-item header-icons navbar-nav-right ms-auto">
                        <li class="dropdown nav-item"> <a class="new nav-link theme-layout nav-link-bg layout-setting">
                                <span class="dark-layout"><svg xmlns="http://www.w3.org/2000/svg"
                                        class="header-icon-svgs" width="24" height="24" viewBox="0 0 24 24">
                                        <path
                                            d="M20.742 13.045a8.088 8.088 0 0 1-2.077.271c-2.135 0-4.14-.83-5.646-2.336a8.025 8.025 0 0 1-2.064-7.723A1 1 0 0 0 9.73 2.034a10.014 10.014 0 0 0-4.489 2.582c-3.898 3.898-3.898 10.243 0 14.143a9.937 9.937 0 0 0 7.072 2.93 9.93 9.93 0 0 0 7.07-2.929 10.007 10.007 0 0 0 2.583-4.491 1.001 1.001 0 0 0-1.224-1.224zm-2.772 4.301a7.947 7.947 0 0 1-5.656 2.343 7.953 7.953 0 0 1-5.658-2.344c-3.118-3.119-3.118-8.195 0-11.314a7.923 7.923 0 0 1 2.06-1.483 10.027 10.027 0 0 0 2.89 7.848 9.972 9.972 0 0 0 7.848 2.891 8.036 8.036 0 0 1-1.484 2.059z">
                                        </path>
                                    </svg></span> <span class="light-layout"><svg xmlns="http://www.w3.org/2000/svg"
                                        class="header-icon-svgs" width="24" height="24" viewBox="0 0 24 24">
                                        <path
                                            d="M6.993 12c0 2.761 2.246 5.007 5.007 5.007s5.007-2.246 5.007-5.007S14.761 6.993 12 6.993 6.993 9.239 6.993 12zM12 8.993c1.658 0 3.007 1.349 3.007 3.007S13.658 15.007 12 15.007 8.993 13.658 8.993 12 10.342 8.993 12 8.993zM10.998 19h2v3h-2zm0-17h2v3h-2zm-9 9h3v2h-3zm17 0h3v2h-3zM4.219 18.363l2.12-2.122 1.415 1.414-2.12 2.122zM16.24 6.344l2.122-2.122 1.414 1.414-2.122 2.122zM6.342 7.759 4.22 5.637l1.415-1.414 2.12 2.122zm13.434 10.605-1.414 1.414-2.122-2.122 1.414-1.414z">
                                        </path>
                                    </svg></span> </a> </li>
                        <li class="dropdown nav-item main-header-notification d-flex"> <a class="new nav-link"
                                data-bs-toggle="dropdown" href="javascript:void(0);"> <svg
                                    xmlns="http://www.w3.org/2000/svg" class="header-icon-svgs" width="24" height="24"
                                    viewBox="0 0 24 24">
                                    <path
                                        d="M19 13.586V10c0-3.217-2.185-5.927-5.145-6.742C13.562 2.52 12.846 2 12 2s-1.562.52-1.855 1.258C7.185 4.074 5 6.783 5 10v3.586l-1.707 1.707A.996.996 0 0 0 3 16v2a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-2a.996.996 0 0 0-.293-.707L19 13.586zM19 17H5v-.586l1.707-1.707A.996.996 0 0 0 7 14v-4c0-2.757 2.243-5 5-5s5 2.243 5 5v4c0 .266.105.52.293.707L19 16.414V17zm-7 5a2.98 2.98 0 0 0 2.818-2H9.182A2.98 2.98 0 0 0 12 22z">
                                    </path>
                                </svg><span class=" pulse"></span> </a>
                            <div class="dropdown-menu">
                                <div class="menu-header-content text-start border-bottom">
                                    <div class="d-flex">
                                        <h6 class="dropdown-title mb-1 tx-15 font-weight-semibold">Notifications
                                        </h6> <span
                                            class="badge badge-pill badge-warning ms-auto my-auto float-end">Mark
                                            All Read</span>
                                    </div>
                                    <p class="dropdown-title-text subtext mb-0 op-6 pb-0 tx-12 ">You have 4
                                        unread Notifications</p>
                                </div>
                                <div class="main-notification-list Notification-scroll ps"> 
                                    <a class="d-flex p-3 border-bottom" href="">
                                        <div class="notifyimg bg-pink"> 
                                            <i class="far fa-folder-open text-white"></i>
                                        </div>
                                        <div class="ms-3">
                                            <h5 class="notification-label mb-1">New files available</h5>
                                            <div class="notification-subtext">10 hour ago</div>
                                        </div>
                                        <div class="ms-auto"> <i class="las la-angle-right text-end text-muted"></i>
                                        </div>
                                    </a>
                                </div>
                                <div class="dropdown-footer"> <a class="btn btn-primary btn-sm btn-block"
                                        href="">VIEW ALL</a> </div>
                            </div>
                        </li>
                        <li class="nav-link search-icon d-lg-none d-block">
                            <form class="navbar-form" role="search">
                                <div class="input-group"> <input type="text" class="form-control" placeholder="Search">
                                    <span class="input-group-btn"> <button type="reset" class="btn btn-default"> <i
                                                class="fas fa-times"></i>
                                        </button> <button type="submit" class="btn btn-default nav-link resp-btn"> <svg
                                                xmlns="http://www.w3.org/2000/svg" height="24px"
                                                class="header-icon-svgs" viewBox="0 0 24 24" width="24px"
                                                fill="#000000">
                                                <path d="M0 0h24v24H0V0z" fill="none"></path>
                                                <path
                                                    d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z">
                                                </path>
                                            </svg> </button> </span> </div>
                            </form>
                        </li>
                        <li class="dropdown main-profile-menu nav nav-item nav-link ps-lg-2"> <a
                                class="new nav-link profile-user d-flex" href="" data-bs-toggle="dropdown"><img alt=""
                                    src="https://cdn-icons-png.flaticon.com/512/666/666201.png" class=""></a>
                            <div class="dropdown-menu">
                                <div class="menu-header-content p-3 border-bottom">
                                    <div class="d-flex wd-100p">
                                        <div class="main-img-user"><img alt="" src="https://cdn-icons-png.flaticon.com/512/666/666201.png" class="">
                                        </div>
                                        <div class="ms-3 my-auto">
                                            <h6 class="tx-15 font-weight-semibold mb-0">{{user}}</h6><span
                                                class="dropdown-title-text subtext op-6  tx-12">Premium
                                                Member</span>
                                        </div>
                                    </div>
                                </div> 
                                <a class="dropdown-item" href="{% url 'base:profile' %}">
                                    <i class="far fa-user-circle"></i>Profile
                                </a> 
                                <a class="dropdown-item" href="{% url 'account_logout' %}">
                                    <i class="far fa-arrow-alt-circle-left"></i> Sign Out
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <div class="jumps-prevent" style="padding-top: 63px;"></div> -->

base/templates/partials/_auth_script.html
{% load static %}
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/chart.js/Chart.bundle.min.js' %}"></script>
<script src="{% static 'plugins/moment/moment.js' %}"></script>
<script src="{% static 'js/apexcharts.js' %}"></script>
<script src="{% static 'plugins/jquery-sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'plugins/raphael/raphael.min.js' %}"></script>
<script src="{% static 'plugins/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'plugins/perfect-scrollbar/p-scroll.js' %}"></script>
<script src="{% static 'js/eva-icons.min.js' %}"></script>
<script src="{% static 'plugins/sidebar/sidebar.js' %}"></script>
<script src="{% static 'plugins/sidebar/sidebar-custom.js' %}"></script>
<script src="{% static 'plugins/side-menu/sidemenu.js' %}"></script>
<script src="{% static 'js/sticky.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/circle-progress.min.js' %}"></script>
<script src="{% static 'plugins/datatable/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatable/js/dataTables.bootstrap5.js' %}"></script>
<script src="{% static 'plugins/datatable/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatable/responsive.bootstrap5.min.js' %}"></script>
<script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'js/select2.js' %}"></script>
<script src="{% static 'js/themecolor.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'switcher/js/switcher.js' %}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

base/templates/partials/_auth_sidebar.html
{% load static i18n %}
<div class="sticky" style="margin-bottom: -63px;">
    <aside class="app-sidebar ps ps--active-y">
        <div class="main-sidebar-header active"> <a class="header-logo active" href="{% url 'base:index' %}"> <img
                    src="{% static 'img/brand/logo.png' %}" class="main-logo  desktop-logo" alt="logo"> <img
                    src="{% static 'img/brand/logo-white.png' %}" class="main-logo  desktop-dark" alt="logo"> <img
                    src="{% static 'img/brand/favicon.png' %}" class="main-logo  mobile-logo" alt="logo"> <img
                    src="{% static 'img/brand/favicon-white.png' %}" class="main-logo  mobile-dark" alt="logo"> </a>
        </div>
        <div class="main-sidemenu is-expanded">
            <div class="slide-left disabled active d-none" id="slide-left"><svg xmlns="http://www.w3.org/2000/svg"
                    fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                    <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"></path>
                </svg></div>
            <ul class="side-menu open" style="margin-right: 0px; margin-left: 0px;">
                <li class="slide"> <a class="side-menu__item" href="{% url 'base:dashboard' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" class="side-menu__icon" width="24" height="24" viewBox="0 0 24 24">
                        <path
                            d="M3 13h1v7c0 1.103.897 2 2 2h12c1.103 0 2-.897 2-2v-7h1a1 1 0 0 0 .707-1.707l-9-9a.999.999 0 0 0-1.414 0l-9 9A1 1 0 0 0 3 13zm7 7v-5h4v5h-4zm2-15.586 6 6V15l.001 5H16v-5c0-1.103-.897-2-2-2h-4c-1.103 0-2 .897-2 2v5H6v-9.586l6-6z">
                        </path>
                    </svg>
                    <span class="side-menu__label">Dashboard</span></a> 
                </li>
                <li class="slide"> <a class="side-menu__item" href="{% url 'wsite:wsites' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" class="side-menu__icon" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M12 2C6.486 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.514 2 12 2zm7.931 9h-2.764a14.67 14.67 0 0 0-1.792-6.243A8.013 8.013 0 0 1 19.931 11zM12.53 4.027c1.035 1.364 2.427 3.78 2.627 6.973H9.03c.139-2.596.994-5.028 2.451-6.974.172-.01.344-.026.519-.026.179 0 .354.016.53.027zm-3.842.7C7.704 6.618 7.136 8.762 7.03 11H4.069a8.013 8.013 0 0 1 4.619-6.273zM4.069 13h2.974c.136 2.379.665 4.478 1.556 6.23A8.01 8.01 0 0 1 4.069 13zm7.381 6.973C10.049 18.275 9.222 15.896 9.041 13h6.113c-.208 2.773-1.117 5.196-2.603 6.972-.182.012-.364.028-.551.028-.186 0-.367-.016-.55-.027zm4.011-.772c.955-1.794 1.538-3.901 1.691-6.201h2.778a8.005 8.005 0 0 1-4.469 6.201z"></path>
                    </svg>
                    <span class="side-menu__label">Sites</span></a> 
                </li>
                <li class="slide"> <a class="side-menu__item" href="{% url 'base:profile' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" class="side-menu__icon" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M12 16c2.206 0 4-1.794 4-4s-1.794-4-4-4-4 1.794-4 4 1.794 4 4 4zm0-6c1.084 0 2 .916 2 2s-.916 2-2 2-2-.916-2-2 .916-2 2-2z"></path>
                        <path d="m2.845 16.136 1 1.73c.531.917 1.809 1.261 2.73.73l.529-.306A8.1 8.1 0 0 0 9 19.402V20c0 1.103.897 2 2 2h2c1.103 0 2-.897 2-2v-.598a8.132 8.132 0 0 0 1.896-1.111l.529.306c.923.53 2.198.188 2.731-.731l.999-1.729a2.001 2.001 0 0 0-.731-2.732l-.505-.292a7.718 7.718 0 0 0 0-2.224l.505-.292a2.002 2.002 0 0 0 .731-2.732l-.999-1.729c-.531-.92-1.808-1.265-2.731-.732l-.529.306A8.1 8.1 0 0 0 15 4.598V4c0-1.103-.897-2-2-2h-2c-1.103 0-2 .897-2 2v.598a8.132 8.132 0 0 0-1.896 1.111l-.529-.306c-.924-.531-2.2-.187-2.731.732l-.999 1.729a2.001 2.001 0 0 0 .731 2.732l.505.292a7.683 7.683 0 0 0 0 2.223l-.505.292a2.003 2.003 0 0 0-.731 2.733zm3.326-2.758A5.703 5.703 0 0 1 6 12c0-.462.058-.926.17-1.378a.999.999 0 0 0-.47-1.108l-1.123-.65.998-1.729 1.145.662a.997.997 0 0 0 1.188-.142 6.071 6.071 0 0 1 2.384-1.399A1 1 0 0 0 11 5.3V4h2v1.3a1 1 0 0 0 .708.956 6.083 6.083 0 0 1 2.384 1.399.999.999 0 0 0 1.188.142l1.144-.661 1 1.729-1.124.649a1 1 0 0 0-.47 1.108c.112.452.17.916.17 1.378 0 .461-.058.925-.171 1.378a1 1 0 0 0 .471 1.108l1.123.649-.998 1.729-1.145-.661a.996.996 0 0 0-1.188.142 6.071 6.071 0 0 1-2.384 1.399A1 1 0 0 0 13 18.7l.002 1.3H11v-1.3a1 1 0 0 0-.708-.956 6.083 6.083 0 0 1-2.384-1.399.992.992 0 0 0-1.188-.141l-1.144.662-1-1.729 1.124-.651a1 1 0 0 0 .471-1.108z"></path>
                    </svg>
                    <span class="side-menu__label">Settings</span></a> 
                </li>
            </ul>
            <div class="slide-right" id="slide-right"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24"
                    height="24" viewBox="0 0 24 24">
                    <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z"></path>
                </svg></div>
        </div>
        <div class="ps__rail-x" style="left: 0px; bottom: 0px;">
            <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
        </div>
        <div class="ps__rail-y" style="top: 0px; height: 625px; right: 0px;">
            <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 437px;"></div>
        </div>
    </aside>
</div>

base/templates/partials/_navbar.html
{% load static %}
<div class="top sticky overflow-hidden">
    <div class="container ">
        <div class="row">
            <div class="col-lg-2 col-md-12 col-sm-12 justify-content-center">
                <div class="logo-demo">
                    <a href="{% url 'base:index' %}"><img alt="" class="logo" src="demo/img/logo-white.png"></a>
                    <a href="{% url 'base:index' %}"><img alt="" class="logo-2" src="demo/img/logo.png"></a>
                </div>
            </div>
            <div class="col-lg-8 col-sm-12 d-none d-lg-flex justify-content-center">
                <ul class="nav navbar-nav nav-pills justify-content-center">
                    <li class="nav-item"><a href="#home" class="active nav-link nav-scroll">Home</a></li>
                    <li class="nav-item"><a href="#features" class="nav-link nav-scroll">About</a></li>
                    <li class="nav-item"><a href="#faqs" class="nav-link nav-scroll">Features</a></li>
                    <li class="nav-item"><a href="#pricings" class="nav-link nav-scroll">Pricing</a>
                    </li>
                    <li class="nav-item"><a href="#contact-page" class="nav-link nav-scroll">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-sm-12 d-none d-lg-flex justify-content-center">
                <div class="header-nav-right">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'base:dashboard' %}"
                        class="btn rounded-pill btn-success-gradient pt-2 pb-2">
                        Dashboard
                    </a>
                    {% else %}
                    <a href="{% url 'account_login' %}"
                        class="btn rounded-pill btn-success-gradient pt-2 pb-2">
                        Login
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>