base/urls.py
from django.urls import path
from base import views


app_name = 'base'

urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("about-us/", views.AboutUsView.as_view(), name='about'),
    path("contact-us/", views.ContactView.as_view(), name='contact'),
    path("dashboard/", views.DashboardView.as_view(), name='dashboard'),
    path("profile/", views.EditUser.as_view(), name='profile'),
]

sdtmonitor/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", include("base.urls", namespace='base')),
    path("accounts/", include("allauth.urls")),
    path("pricing/", include("plan.urls", namespace='plans')),
    path("wsites/", include("wsite.urls", namespace='wsites')),
    path("admin/", admin.site.urls),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    extrapatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

    urlpatterns += extrapatterns

wsite/urls.py
from django.urls import path
from wsite import views, ajax_views


app_name = 'wsite'

urlpatterns = [
    path('', views.ListWebsiteView.as_view(), name='wsites'),
    path('create-site/', views.CreateWebsiteView.as_view(), name='create-site'),
    path('<str:slug>/', views.RetrieveWebsiteView.as_view(), name='site'),
    path('<str:slug>/add-email/', ajax_views.AddEmailView.as_view(), name='add-email'),
    path('<str:slug>/remove-email/', ajax_views.RemoveEmailView.as_view(), name='remove-email'),
    path('<str:slug>/delete/', views.DeleteWebsiteView.as_view(), name='delete-site'),
]

wsite/models.py
import auto_prefetch
from django.db import models
from sdtmonitor.utils.models import NameTimeBasedModel, TimeBasedModel, StatusModel
from sdtmonitor.utils.strings import get_slug_text
# Create your models here.


class Website(NameTimeBasedModel, StatusModel):
    user = auto_prefetch.ForeignKey('base.User', on_delete=models.CASCADE)
    url = models.URLField()
    slug = models.SlugField(default=get_slug_text)
    
    def __str__(self):
        return f'{self.name} site by {self.user}'
    
    def get_color(self):
        return 'success' if self.status == 'up' else 'danger'
    
    def emails(self):
        return self.websiteemail_set.all()


class WebsiteLog(TimeBasedModel, StatusModel):
    site = auto_prefetch.ForeignKey('wsite.Website', on_delete=models.CASCADE)

    def __str__(self):
        return ''


class WebsiteEmail(TimeBasedModel):
    site = auto_prefetch.ForeignKey('wsite.Website', on_delete=models.CASCADE)
    email = models.EmailField()

    def __str__(self):
        return f'{self.email} is watching {self.site}'

wsite/forms.py
from django import forms
from sdtmonitor.utils.forms import CssForm
from wsite.models import Website

class WebsiteForm(forms.ModelForm, CssForm):
    class Meta:
        model = Website
        exclude = ['user', 'status', 'slug']

wsite/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, ListView, View, DetailView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from wsite.models import Website
from wsite.forms import WebsiteForm
from sdtmonitor.settings.local.email_settings import SERVER_EMAIL
# Create your views here.


class ListWebsiteView(LoginRequiredMixin, ListView):
    template_name = 'wsite/list.html'
    paginate_by = 15
    context_object_name = 'websites'
    
    def get_queryset(self):
        return Website.objects.filter(user=self.request.user)


class CreateWebsiteView(LoginRequiredMixin, CreateView):
    template_name = 'wsite/create.html'
    form_class = WebsiteForm
    model = Website

    def form_valid(self, form):
        request = self.request
        website = form.save(commit=False)
        website.user = request.user
        website.save()
        messages.success(
            request,
            f"Website {website.name} successfully added for monitor",
        )
        msg_to_user = (
            f"Hi {request.user}\n\n" +
            f"Site {website.name} has been added to your watch list" +
            f"You can proceed with your day to day activity while we help you watch it")

        send_mail(
            subject="New Site Added to Watch List",
            message=msg_to_user,
            fail_silently=True,
            from_email=SERVER_EMAIL,
            recipient_list=[request.user.email],
        )

        return redirect("wsite:wsites")


class RetrieveWebsiteView(LoginRequiredMixin, DetailView):
    template_name = 'wsite/detail.html'
    slug_url_kwarg = 'slug'
    model = Website



class DeleteWebsiteView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        sites = get_object_or_404(Website, slug=self.kwargs['slug'])
        sites.delete()
        messages.success(
            request,
            f"Website removed from watchlist",
        )
        return redirect("wsite:wsites")

wsite/templates/wsite/create.html
{% extends 'partials/_auth_layout.html' %}
{% load static i18n %}
{% block title %}Add Site{% endblock title  %}
{% block breadcrumb_title %}Add Site{% endblock breadcrumb_title %}
{% block content %}
<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header pb-0">
                <div class="d-flex justify-content-between">
                    <!-- <h4 class="card-title mg-b-0">Hoverable Rows Table</h4> -->
                </div>
                <p class="tx-12 tx-gray-500 mb-2">Website URL must carry the http protocol for it to be added</p>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% include "partials/_messages.html" %}
                    {% include "partials/_form_errors.html" %}
                    {{form.as_p}}
                    <div>
                        <button class="btn btn-primary" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

wsite/templates/wsite/detail.html
{% extends 'partials/_auth_layout.html' %}
{% load static i18n %}
{% block title %}{{website.name}}{% endblock title  %}
{% block breadcrumb_title %}{{website.name}}{% endblock breadcrumb_title %}
{% block content %}
<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header pb-0">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title mg-b-0">Site {{website.name}}</h4>
                    <!-- <a href="{% url 'wsites:create-site' %}" class="btn btn-primary btn-sm">Add Site</a> -->
                </div>
                <p class="tx-12 tx-gray-500 mb-2">

                </p>
            </div>
            <div class="card-body">
                <h6>Logs from {{website.name}} watch</h6>
            </div>
        </div>
    </div>
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header pb-0">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title mg-b-0">Emails Associated to {{website.name}} watch</h4>
                    <a  data-bs-toggle="modal" data-bs-target="#staticBackdrop" class="btn btn-primary btn-sm">Add Email</a>
                    <!-- <a href="{% url 'wsites:create-site' %}" class="btn btn-primary btn-sm">Add Site</a> -->
                </div>
                <p class="tx-12 tx-gray-500 mb-2">

                </p>
            </div>
            <div class="card-body">
                {% if website.emails %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover mb-0 text-md-nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for email in website.emails %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{email}}</td>
                                <td>
                                    <button data-email="{{email.email}}" onclick="removeEmail(this)" class="btn btn-outline-danger btn-sm">Remove</button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <p>No Emails Added Yet! <a  class="text-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Add Email</a></p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <form action="" method="post" id="email-form">
            
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Add Email to {{website.name}}</h5>
                <button type="button" class="text-danger" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <label for="">Email</label>
                <input type="email" name="email" class="form-control" id="">
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Add Email</button>
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
              </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}
{% block extra_scripts %}
<script type="text/javascript">
document.getElementById('email-form').addEventListener('submit', e => {
    e.preventDefault();
    const {value} = e.target[1]
    data = new FormData()
    $.ajax({
        url : `{% url 'wsite:add-email' 1200 %}`.replace(1200, '{{website.slug}}'),
        method : 'POST',
        headers : {
            "X-CSRFToken" : '{{csrf_token}}'
        },
        data : {'email' : value}
    })
    .then(data => {
        $('#staticBackdrop').modal('hide')
        swal({"text" : data.msg, "icon": "success"})
        .then((value) => {
            window.location.reload()
        });
    })
    .catch(err => {
        $('#staticBackdrop').modal('hide')
        swal({"text" : "Error Adding Email", "icon": "error"})
    })
    
})


const removeEmail = (e)=> {
    const {email} = e.dataset
    $.ajax({
        url : `{% url 'wsite:remove-email' 1200 %}`.replace(1200, '{{website.slug}}'),
        method : 'POST',
        headers : {
            "X-CSRFToken" : '{{csrf_token}}'
        },
        data : {'email' : email}
    })
    .then(data => {
        $('#staticBackdrop').modal('hide')
        swal({"text" : data.msg, "icon": "success"})
        .then((value) => {
            window.location.reload()
        });
    })
    .catch(err => swal({"text" : "Error Removing Email", "icon": "error"}))
}
</script>

{% endblock extra_scripts %}

wsite/templates/wsite/list.html
{% extends 'partials/_auth_layout.html' %}
{% load static i18n %}
{% block title %}My Sites{% endblock title  %}
{% block breadcrumb_title %}My Sites{% endblock breadcrumb_title %}
{% block content %}
<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header pb-0">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title mg-b-0">Sites Under your watch</h4>
                    <a href="{% url 'wsites:create-site' %}" class="btn btn-primary btn-sm">Add Site</a>
                </div>
                <p class="tx-12 tx-gray-500 mb-2">

                </p>
            </div>
            <div class="card-body">
                {% if websites %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover mb-0 text-md-nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>URL</th>
                                <th>Status</th>
                                <th>Func</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for website in websites %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{website.name}}</td>
                                <td>{{website.url}}</td>
                                <td class="text-center"><span class="badge bg-{{website.get_color}}">{{website.status}}</span></td>
                                <td>
                                    <a href="{% url 'wsites:site' website.slug %}" class="btn btn-primary btn-sm">View</a>
                                    <a href="{% url 'wsites:delete-site' website.slug %}" class="btn btn-outline-danger btn-sm">Delete</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <p>No Site under your watch Yet! <a href="{% url 'wsites:create-site' %}" class="text-danger">Add to WatchList</a></p>
                {% endif %}
            </div>
        </div>
    </div>
</div>


{% endblock content %}